spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/bzrspace}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
  liquibase:
    change-log: db/changelog/changelog-master.yaml
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KC_URL:http://localhost:9999}/realms/${KC_REALM:bazar-realm}
  threads:
    virtual:
      enabled: true
  cache:
    type: caffeine
  kafka:
    enabled: true
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    security:
      protocol: SASL_PLAINTEXT
    topics:
      producers:
        space-events:
          name: space.events
          enabled: true
    properties:
      security.protocol: SASL_SSL
      sasl.mechanism: SCRAM-SHA-512
      sasl.jaas.config: >
        org.apache.kafka.common.security.scram.ScramLoginModule required
        username="${KAFKA_USERNAME}"
        password="${KAFKA_PASSWORD}";
server:
  servlet:
    context-path: /api
  port: 8080
management:
  server:
    port: 8090
logging:
  level:
    org:
      bazar: ${LOGGING_LEVEL:DEBUG}
authorization:
  port: ${BAZAR_AUTHORIZATION_PORT:9090}
  host: ${BAZAR_AUTHORIZATION_HOST:localhost}
rest:
  clients:
    bazar-persona-url: ${BAZAR_PERSONA_API_URL:http://localhost:8081/api}
    bazar-authz-url: ${BAZAR_AUTHORIZATION_API_URL:http://localhost:8082/api}